spring:
  application:
    name: wang-mybatis-plus
  #数据库连接相关配置
  datasource:
    url: jdbc:mysql://192.168.1.237:3306/shop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root123
    #阿里巴巴的druid的mysql连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver