server:
  port: 8089
spring:
  application:
    name: wang-webs
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: 10
    timeout: 3000
    lettuce:
      pool:
        max-active: 500
        min-idle: 1
        max-idle: 32
        max-wait: 1500
  cache:
    type: redis