spring:
  application:
    name: wang-product
  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///wang_basic?serverTimezone=UTC&characterEncoding=utf-8&useSSL=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
server:
  port: 8011