server:
  port: 8021

spring:
  application:
    name: wang-product-nacos
  cloud:
    nacos:
      server-addr: 42.193.109.161:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
#    sentinel:
#      transport:
#        port: 9021
#        dashboard: localhost:8080


